@APP_SITE = https://best-practices-demo-appserver-js.onrender.com
@AUTH_SITE = https://best-practices-demo-authserver-js.onrender.com
###
# @name login
# POST http://localhost:5000/login
POST {{AUTH_SITE}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
###
@ACCESS_TOKEN =  {{login.response.headers.auth-token-access}}
@REFRESH_TOKEN = {{login.response.headers.auth-token-refresh}}
###
GET {{APP_SITE}}/api/v1/pokemon?id=77&appid
auth-token-access : {{ACCESS_TOKEN}}
###
GET {{APP_SITE}}/report?id=3
auth-token-access : {{ACCESS_TOKEN}}
###
# @name requestNewAccessToken
POST {{AUTH_SITE}}/requestNewAccessToken
Content-Type: application/json
auth-token-refresh : {{REFRESH_TOKEN}}
###
@NEW_ACCESS_TOKEN =  {{requestNewAccessToken.response.headers.auth-token-access}}
###
GET {{APP_SITE}}api/v1/pokemon?id=77
auth-token-access:{{NEW_ACCESS_TOKEN}}



