POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "email": "test@test.ca"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

GET http://localhost:6000/api/v1/pokemon/77
auth-token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzY0MTNiZjc3NTM1MWM5ODJjN2JmNTciLCJpYXQiOjE2Njc1MDMwNTR9.Roe2sx28XA88BH501loULxvL_hvQ2i3dKeu6Rnr5H8k"

###